2025-03-19 10:11:01,591 - ERROR - API Call Failed: search_products: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 10:11:01,600 - ERROR - Error occurred: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 10:16:59,557 - ERROR - API Call Failed: search_products: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 10:16:59,557 - ERROR - Error occurred: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 10:21:15,131 - ERROR - API Call Failed: search_products: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 10:21:15,131 - ERROR - Error occurred: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 11:16:43,900 - ERROR - 搜索引擎调用失败: {'request_info': {'args': {'query': '米', 'limit': '100', 'page': '1'}, 'headers': {'User-Agent': 'Apifox/1.0.0 (https://apifox.com)', 'Accept': '*/*', 'Host': '127.0.0.1:7199', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive'}, 'method': 'GET', 'path': '/search', 'url': 'http://127.0.0.1:7199/search?query=米&limit=100&page=1', 'remote_addr': '127.0.0.1', 'user_agent': 'Apifox/1.0.0 (https://apifox.com)'}, 'search_params': {'query': '米', 'limit': 100, 'page': 1, 'top_k': 1000}, 'error': "int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'response': {'code': 500, 'message': "搜索引擎错误: int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'data': None}}
Traceback (most recent call last):
  File "E:\pkuseg\app\routes\search_routes.py", line 83, in search_products
    results = search_engine.search(
  File "E:\pkuseg\app\services\search_engine.py", line 168, in search
    products = [
  File "E:\pkuseg\app\services\search_engine.py", line 171, in <listcomp>
    if int(self.products[pid]['zone_rule_id']) == int(zone_rule_id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2025-03-19 11:16:43,900 - ERROR - API Call Failed: search_products: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 11:16:43,902 - ERROR - Error occurred: Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\pkuseg\.venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\pkuseg\utils\logger_handler.py", line 172, in decorated_function
    self.log_info(f"API Call Success: {f.__name__}", log_data)
  File "E:\pkuseg\utils\logger_handler.py", line 129, in log_info
    message = f"{message} - {json.dumps(extra)}"
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\python-verser\pyenv-win-master\pyenv-win\versions\3.8.0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2025-03-19 11:17:56,898 - ERROR - 搜索引擎调用失败: {'request_info': {'args': {'query': '米', 'limit': '100', 'page': '1'}, 'headers': {'User-Agent': 'Apifox/1.0.0 (https://apifox.com)', 'Accept': '*/*', 'Host': '127.0.0.1:7199', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive'}, 'method': 'GET', 'path': '/search', 'url': 'http://127.0.0.1:7199/search?query=米&limit=100&page=1', 'remote_addr': '127.0.0.1', 'user_agent': 'Apifox/1.0.0 (https://apifox.com)'}, 'search_params': {'query': '米', 'limit': 100, 'page': 1, 'top_k': 1000}, 'error': "int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'response': {'code': 500, 'message': "搜索引擎错误: int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'data': None}}
Traceback (most recent call last):
  File "E:\pkuseg\app\routes\search_routes.py", line 83, in search_products
    results = search_engine.search(
  File "E:\pkuseg\app\services\search_engine.py", line 168, in search
    products = [
  File "E:\pkuseg\app\services\search_engine.py", line 171, in <listcomp>
    if int(self.products[pid]['zone_rule_id']) == int(zone_rule_id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2025-03-19 11:20:49,599 - ERROR - 搜索引擎调用失败: {'request_info': {'args': {'query': '米', 'limit': '100', 'page': '1'}, 'headers': {'User-Agent': 'Apifox/1.0.0 (https://apifox.com)', 'Accept': '*/*', 'Host': '127.0.0.1:7199', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive'}, 'method': 'GET', 'path': '/search', 'url': 'http://127.0.0.1:7199/search?query=米&limit=100&page=1', 'remote_addr': '127.0.0.1', 'user_agent': 'Apifox/1.0.0 (https://apifox.com)'}, 'search_params': {'query': '米', 'limit': 100, 'page': 1, 'top_k': 1000}, 'error': "int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'response': {'code': 500, 'message': "搜索引擎错误: int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'data': None}}
Traceback (most recent call last):
  File "E:\pkuseg\app\routes\search_routes.py", line 83, in search_products
    results = search_engine.search(
  File "E:\pkuseg\app\services\search_engine.py", line 168, in search
    products = [
  File "E:\pkuseg\app\services\search_engine.py", line 171, in <listcomp>
    if int(zone_rule_id) == int(self.products[pid].get('zone_rule_id', 0))  # 如果获取不到值或为None，默认为0
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2025-03-19 11:20:52,954 - ERROR - 搜索引擎调用失败: {'request_info': {'args': {'query': '米', 'limit': '100', 'page': '1'}, 'headers': {'User-Agent': 'Apifox/1.0.0 (https://apifox.com)', 'Accept': '*/*', 'Host': '127.0.0.1:7199', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive'}, 'method': 'GET', 'path': '/search', 'url': 'http://127.0.0.1:7199/search?query=米&limit=100&page=1', 'remote_addr': '127.0.0.1', 'user_agent': 'Apifox/1.0.0 (https://apifox.com)'}, 'search_params': {'query': '米', 'limit': 100, 'page': 1, 'top_k': 1000}, 'error': "int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'response': {'code': 500, 'message': "搜索引擎错误: int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'data': None}}
Traceback (most recent call last):
  File "E:\pkuseg\app\routes\search_routes.py", line 83, in search_products
    results = search_engine.search(
  File "E:\pkuseg\app\services\search_engine.py", line 168, in search
    products = [
  File "E:\pkuseg\app\services\search_engine.py", line 171, in <listcomp>
    if int(zone_rule_id) == int(self.products[pid].get('zone_rule_id', 0))  # 如果获取不到值或为None，默认为0
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
